on:
  workflow_dispatch:
  release:
    types:
      - created

name: Upload Release Asset

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'ICRPG_EffortOverride.ext'
        exclusions: '*.git* /*node_modules/* .editorconfig'
